name: CI

# This workflow run tests and build for each push

on:
  push:
    branches:
      - main
      - 'feature-**'

jobs:
  test and build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # The nightly pinning is because otherwise rustfmt is not always present
      # https://rust-lang.github.io/rustup-components-history/
      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install nightly-2021-03-25
          rustup component add rustfmt --toolchain nightly-2021-03-25


      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      # - name: Lint
      #   run: |
      #     make lint

      - name: Test
        # make test
        run: |
          make check

      - name: Build
        run: make build
